dist: bionic
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - cppcheck
      - python3-venv
      - wget
services:
  - docker
before_install:
  - wget -O gcc-arm.tar.bz2 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2?revision=6e63531f-8cb1-40b9-bbfc-8a57cdfc01b4&la=en&hash=F761343D43A0587E8AC0925B723C04DBFB848339'
  - sudo tar -jxf gcc-arm.tar.bz2 --strip-components=1 -C /
  - rm gcc-arm.tar.bz2
script:
  - export CC=gcc-8
  - make travis
